
services:
  mysql:
    image: 'mysql:latest'
    container_name: 'flextime'
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    env_file:
      - .env
    ports:
      - '3306:3306'
